[package]
name = "gipny-agent"
version = "0.4.3"
edition = "2021"
publish = false
description = "Headless Gipny console agent"

[[bin]]
name = "gipny-agent"
path = "src/main.rs"

[dependencies]
gipny-libcore = { path = "../libcore" }
tokio = { workspace = true }
anyhow = "1"
bincode = { workspace = true }
